coverage:
  ignore:
    - tests/.*
  status:
    patch: false
    project:
      default:
        threshold: 80%
	target: 0%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: once
  flags: null
  paths: null
