coverage:
  ignore:
    - tests/.*
  status:
    patch:
      default:
        target: 50%
    project:
      default:
        threshold: 80%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: once
  flags: null
  paths: null
