name: Build and Deploy Docs

on:
  push:
    branches:
      - docs

permissions: write-all

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for tag/version

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install package
        shell: bash -l {0}
        working-directory: .
        run: |
          cd docs
          python -m pip install -r requirements.txt

      - name: Build Documentation
        shell: bash -l {0}
        working-directory: .
        run: |
          cd docs
          make html

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/_build/html
          branch: gh-pages
