name: Build and Deploy Docs

on:
  push:
    branches:
      - sphinx-docs

permissions: write-all

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # needed for tag/version

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install package
        shell: bash -l {0}
        working-directory: .
        run: |
          python -m pip install -r sphinx-docs/requirements.txt

      - name: Install Doxygen
        shell: bash -l {0}
        working-directory: .
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Build Documentation
        shell: bash -l {0}
        working-directory: .
        run: |
          cd sphinx-docs
          make html

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: sphinx-docs/_build/html
          branch: gh-pages